export const APP_TEXT = {
  auth: {
    errors: {
      tryAgain: 'Try again.',
      sendOtpFailed: 'Could not send OTP',
      verifyFailed: 'Verification failed',
      resendFailed: 'Resend failed',
      onboardingFailed: 'Onboarding failed',
    },
    phoneLogin: {
      title: 'Join as a Dellite Partner!',
      subtitle: 'Enter your phone number to start getting work',
      countryCode: 'IN +91',
      phonePlaceholder: 'Enter your 10-digit phone number',
      sendOtpButton: 'Send OTP',
      securePrivate: 'Secure & Private',
      noSpam: 'No Spam',
      terms: 'By continuing, you agree to our Terms of Service & Privacy Policy',
    },
    otpVerification: {
      title: 'Verify Your Number',
      codeSentPrefix: "We've sent a 4-digit code to ",
      resendPrefix: 'Resend code in ',
      resendSuccessTitle: 'OTP sent',
      resendSuccessMessage: 'A new OTP has been sent to your phone.',
      verifyButton: 'Verify & Continue',
      helpText: "Didn't receive the code? Check your SMS inbox or try resending",
    },
  },
  onboarding: {
    identity: {
      step: 'STEP 1 OF 5',
      titlePrefix: 'Tell us about',
      gradientWord: 'yourself',
      subtitle: "We'll personalize your experience based on this info",
      uploadPhotoTitle: 'Add profile photo',
      uploadPhotoSubtitle: 'You can upload your picture in the next update.',
      firstNameLabel: 'First Name',
      firstNamePlaceholder: 'First Name',
      lastNameLabel: 'Last Name',
      lastNamePlaceholder: 'Last Name',
      genderLabel: 'Gender',
      referralCodeLabel: 'Referral Code (Optional)',
      referralCodePlaceholder: 'Enter referral code',
      aadhaarFrontLabel: 'Aadhaar Front',
      aadhaarBackLabel: 'Aadhaar Back',
      aadhaarUploadHint: 'Required for account verification',
      aadhaarUploadButton: 'Upload File',
      nextButton: 'Next',
    },
    aadhaar: {
      step: 'STEP 2 OF 5',
      title: 'Verify Aadhaar',
      subtitle: 'Scan your Aadhaar Secure QR to verify identity instantly.',
    },
    vehicle: {
      step: 'STEP 3 OF 5',
      title: 'Choose your services',
      subtitle: 'Select services you can provide in your city',
      searchPlaceholder: 'Search categories...',
      saveServicesButton: 'Save Selected Services',
      skipButton: 'Skip For Now',
      certificatesTitle: 'Certificates Required',
      certificatesSubtitle: 'Some selected services need certificates before approval.',
      continueButton: 'Continue',
      noCertificateText: 'No certificate required for selected services.',
      selectedCountSuffix: 'services selected',
    },
    certification: {
      step: 'STEP 4 OF 5',
      title: 'Certificates Required',
      subtitle: 'Upload required certificates to complete onboarding.',
      continueButton: 'I Have Uploaded Certificates',
      skipButton: 'Skip For Now',
      noCertificateText: 'No certificate is currently required. Continue to refresh status.',
    },
    welcome: {
      step: 'STEP 5 OF 5',
      title: "You're All Set!",
      subtitle: 'Your profile is ready. Start earning today!',
      button: 'Start Earning',
      autoRedirectLabel: 'You will continue in 5 seconds',
      benefits: {
        locality: 'Get jobs from your locality',
        schedule: 'Earn on your own schedule',
        reputation: 'Build your reputation',
      },
    },
  },
  tabs: {
    homeLabel: 'Home',
    ongoingLabel: 'Ongoing',
    earningsLabel: 'Earnings',
    profileLabel: 'Profile',
  },
  home: {
    title: 'Home',
    welcomePrefix: 'Welcome, ',
    welcomeFallbackName: 'Partner',
    welcomeSuffix: '.',
    subtitle: 'Daily summary, quick actions, and assigned tasks will appear here.',
  },
  ongoing: {
    title: 'Ongoing',
    subtitle: 'Active orders, route progress, and live task updates will show here.',
  },
  earnings: {
    title: 'Earnings',
    subtitle: 'Weekly earnings, payout status, and transaction history will be listed here.',
  },
  profile: {
    title: 'Profile',
    roleLabel: 'Worker',
    memberSincePrefix: 'Member since',
    phoneLabel: 'Phone:',
    nameLabel: 'Name:',
    emailLabel: 'Email',
    contactInfoTitle: 'Contact Info',
    phoneFallback: 'Not available',
    nameFallback: 'Not set',
    notProvided: 'Not provided',
    editProfileButton: 'Edit Profile',
    payoutDetailsButton: 'Payout Details',
    bankInfoButton: 'Bank Account Info',
    allSkillsButton: 'All Skills',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Profile preferences',
    helpTitle: 'Help & Support',
    helpSubtitle: 'Get support and report issues',
    logoutTitle: 'Logout',
    logoutSubtitle: 'Sign out from this device',
    helpSupportButton: 'Help & Support',
    logoutButton: 'Logout',
    edit: {
      step: 'UPDATE PROFILE',
      titlePrefix: 'Update your',
      titleGradientWord: 'profile',
      subtitle: 'Keep your details accurate for better trust and job matching.',
      title: 'Edit Profile',
      fullNamePlaceholder: 'Full Name',
      emailPlaceholder: 'Email Address',
      saveButton: 'Save Changes',
    },
    payout: {
      title: 'Bank Account Info',
      subtitle: 'Add payout details using UPI or bank account.',
      methodTypeLabel: 'Payout Method',
      upiOption: 'UPI',
      bankOption: 'Bank Account',
      upiLabel: 'UPI ID',
      upiPlaceholder: 'name@bank',
      accountHolderLabel: 'Account Holder Name',
      accountHolderPlaceholder: 'Full name as per bank account',
      accountLabel: 'Bank Account Number',
      accountPlaceholder: 'Enter bank account number',
      ifscLabel: 'IFSC Code',
      ifscPlaceholder: 'SBIN0001234',
      fetchError: 'Unable to load bank info.',
      createButton: 'Save Bank Info',
      updateButton: 'Update Bank Info',
      upiHint: 'Use a valid UPI ID linked to your active bank account.',
      bankHint: 'Enter accurate account number and IFSC to avoid payout failures.',
      updatedAtPrefix: 'Last updated: ',
      upiRequired: 'UPI ID is required',
      accountHolderRequired: 'Account holder name is required',
      accountRequired: 'Bank account number is required',
      ifscRequired: 'IFSC code is required',
    },
    helpSupport: {
      title: 'Help & Support',
      subtitle: 'Support chat, FAQs, and contact channels can be added here.',
    },
    allSkills: {
      title: 'All Skills',
      subtitle: 'View your registered services and approval status.',
    },
    referral: {
      title: 'Referral',
      menuTitle: 'Referral Program',
      menuSubtitle: 'View code and reward details',
      pageTitle: 'Refer & Earn',
      pageSubtitle: 'Invite friends and earn rewards',
      heroTitle: 'Refer & Earn',
      heroSubtitle: 'Share the love, earn rewards!',
      conversionSubtitle: 'Redeem coins for real value',
      howItWorksTitle: 'How it works',
      inviteCustomerTitle: 'Invite a Customer',
      inviteWorkerTitle: 'Invite a Worker',
      youLabelPrefix: 'YOU',
      newCustomerLabel: 'NEW CUSTOMER',
      newWorkerLabel: 'NEW WORKER',
      andLabel: 'AND',
      worthPrefix: 'Worth',
      signupLabel: 'On signup',
      triggerPillPrefix: 'On',
      shareButton: 'Share with Friends',
      codeLabel: 'Your Referral Code',
      codeFallback: 'Not available',
      copyButton: 'Copy Code',
      copySuccess: 'Referral code copied',
      infoTitle: 'How it works',
      infoText: 'Share this code with friends. Rewards are applied based on whether they join as customer or worker.',
      rewardsTitle: 'Reward Breakdown',
      rewardCustomerLabel: 'When referred user joins as CUSTOMER',
      rewardWorkerLabel: 'When referred user joins as WORKER',
      rewardUnavailable: 'Reward details will appear here soon.',
      bothRolesRuleTitle: 'Both Roles Rule',
    },
  },
} as const;
