export const APP_TEXT = {
  common: {
    edit: 'Edit',
    fileUpload: {
      pdfSelected: 'PDF selected',
      photoSelected: 'Photo selected',
    },
  },
  network: {
    offlineTitle: 'No internet connection',
    offlineSubtitle: 'Turn on mobile data or Wi-Fi to continue.',
    openSettingsButton: 'Turn On Data or Wi-Fi',
    retryButton: 'Try Again',
    retryStillOffline: 'Still offline. Please turn on internet and try again.',
    retryBackOnline: 'You are back online.',
  },
  auth: {
    errors: {
      tryAgain: 'Try again.',
      sendOtpFailed: 'Could not send OTP',
      verifyFailed: 'Verification failed',
      resendFailed: 'Resend failed',
      onboardingFailed: 'Onboarding failed',
    },
    phoneLogin: {
      title: 'Join as a Dellite Partner!',
      subtitle: 'Enter your phone number to start getting work',
      countryCode: 'IN +91',
      phonePlaceholder: 'Enter your 10-digit phone number',
      sendOtpButton: 'Send OTP',
      securePrivate: 'Secure & Private',
      noSpam: 'No Spam',
      terms: 'By continuing, you agree to our Terms of Service & Privacy Policy',
    },
    otpVerification: {
      title: 'Verify Your Number',
      codeSentPrefix: "We've sent a 4-digit code to ",
      resendPrefix: 'Resend code in ',
      resendSuccessTitle: 'OTP sent',
      resendSuccessMessage: 'A new OTP has been sent to your phone.',
      verifyButton: 'Verify & Continue',
      helpText: "Didn't receive the code? Check your SMS inbox or try resending",
    },
  },
  onboarding: {
    identity: {
      step: 'STEP 1 OF 3',
      titlePrefix: 'Tell us about',
      gradientWord: 'yourself',
      subtitle: "We'll personalize your experience based on this info",
      uploadPhotoTitle: 'Add profile photo',
      uploadPhotoSubtitle: 'Max 2MB',
      firstNameLabel: 'First Name',
      firstNamePlaceholder: 'First Name',
      lastNameLabel: 'Last Name',
      lastNamePlaceholder: 'Last Name',
      genderLabel: 'Gender',
      referralCodeLabel: 'Referral Code (Optional)',
      referralCodePlaceholder: 'Enter referral code',
      aadhaarFrontLabel: 'Aadhaar Front',
      aadhaarBackLabel: 'Aadhaar Back',
      aadhaarUploadHint: 'Required for account verification',
      aadhaarUploadButton: 'Upload File',
      nextButton: 'Next',
    },
    vehicle: {
      step: 'STEP 2 OF 3',
      title: 'Choose your skills',
      subtitle: 'Select skills you can provide in your city',
      selectTitlePrefix: 'Choose Your',
      selectTitleHighlight: 'Skills',
      addMoreTitle: 'Pick your services',
      addMoreSubtitle: 'Expand a category, choose a subcategory, then tap the services you can provide.',
      loadErrorTitle: 'Could not load services',
      loadErrorDescription: 'Pull to refresh or tap retry.',
      emptyServicesTitle: 'No services available',
      emptyServicesDescription: 'Please try again after refreshing.',
      saveServicesButton: 'Save Selected Skills',
      skipButton: 'Skip For Now',
      certificatesTitle: 'Certificates Required',
      certificatesSubtitle: 'Some selected skills need certificates before approval.',
      continueButton: 'Continue',
      noCertificateText: 'No certificate required for selected skills.',
      selectedCountSuffix: 'skills selected',
    },
    certification: {
      step: 'STEP 3 OF 3',
      title: 'Upload Certificates',
      titlePrefix: 'Upload',
      titleHighlight: 'Certificates',
      subtitle: 'Upload required certificates to complete onboarding.',
      continueButton: 'I Have Uploaded Certificates',
      skipButton: 'Skip For Now',
      noCertificateText: 'No certificate is currently required. Continue to refresh status.',
      uploadAndContinueButton: 'Upload and Continue',
      waitingTitle: 'All set. Waiting for approval.',
      waitingSubtitle: 'Certificates are submitted. Admin will verify and approve soon.',
      emptyContinueHint: 'You can continue and add certificates later.',
    },
    welcome: {
      step: 'WELCOME',
      title: "You're All Set!",
      subtitle: 'Your profile is ready. Start earning today!',
      button: 'Start Earning',
      autoRedirectLabel: 'You will continue in 5 seconds',
      benefits: {
        locality: 'Get jobs from your locality',
        schedule: 'Earn on your own schedule',
        reputation: 'Build your reputation',
      },
    },
  },
  tabs: {
    homeLabel: 'Home',
    earningsLabel: 'Earnings',
    profileLabel: 'Profile',
  },
  home: {
    logoAlt: 'Dellite',
    cityFallback: 'Current City',
    welcomeBack: 'Welcome back',
    welcomeFallbackName: 'Partner',
    reviewsSuffix: 'reviews',
    jobFallback: 'Job',
    loadError: 'Unable to load home data right now.',
    loadingLocation: 'Fetching location...',
    locationAccess: {
      title: 'Allow location access',
      subtitle: 'We use your location to show nearby jobs and city availability.',
      actionLabel: 'Allow location',
      helpText: 'You can turn this off later in device settings.',
      noLocationLabel: 'No Location',
    },
    todayJobsLabel: "Today's Jobs",
    earningsLabel: "Today's Earnings",
    growthLabel: "Today's Growth",
    ongoingJobs: {
      title: 'Ongoing jobs',
      subtitle: 'Tap any card to view status, customer, and payout.',
    },
      nearbyJobsTitle: 'Available Jobs Nearby',
      nearbyJobsEmpty: 'No nearby jobs available right now.',
      nearbyJobsLoading: 'Loading nearby jobs...',
      nearbyJobCard: {
      bookingTypeFallback: 'Booking',
      totalAmountLabel: 'Total',
      payoutLabel: 'Your Payout',
    },
    footerMadeWith: 'Made with',
    footerFrom: 'from',
    footerRegionFallback: 'Your City',
    footerCopyrightFallback: '© 2026 Dellite. All rights reserved.',
    currentStatusActiveValue: 'ACTIVE',
    liveTracking: {
      title: 'Worker Live Location',
      onlineButton: 'Go Online',
      offlineButton: 'Go Offline',
      statusOnline: 'Online',
      statusOffline: 'Offline',
      trackingOn: 'Tracking On',
      trackingOff: 'Tracking Off',
      vehicleModeTitle: 'Coming by',
      vehicleModeCar: 'Car',
      vehicleModeTwoWheeler: 'Bike',
      vehicleModeCycle: 'Cycle',
      vehicleModeWalk: 'Walk',
      vehicleModeUnknown: 'Unknown',
      unavailableWorkerId: 'Worker ID unavailable',
      unknownCoordinates: '--',
      bookingPlaceholder: 'None',
      actionFailed: 'Could not update live location state.',
    },
  },
  jobs: {
    titlePrefix: 'My',
    titleHighlight: 'Jobs',
    subtitle: 'Track all jobs from new invites to completed work.',
    availableJobsTitle: 'Available jobs',
    availableJobsSubtitle: 'New job requests waiting for your response.',
    emptyTitle: 'No jobs found',
    emptyDescription: 'No jobs are available in this category right now.',
    availableJobsEmptyTitle: 'No new jobs',
    availableJobsEmptyDescription: 'Fresh job requests will appear here when customers book nearby.',
    cardBookingStatusLabel: 'Booking Status',
    cardInviteStatusLabel: 'Invite Status',
    cardTotalBillLabel: 'Total Bill',
    cardWorkerEarningLabel: 'Your Earning',
    cardPaymentStatusLabel: 'Payment Status',
    cardViewAction: 'View Job',
    liveLocation: {
      movingTitle: 'You are live',
      movingSubtitle: 'Customer can track your location',
      stationaryTitle: 'You are online',
      stationarySubtitle: 'Location is not changing right now',
      weakTitle: 'GPS signal is weak',
      weakSubtitle: 'Move to open area or check location permission',
      updatingTitle: 'Checking your location',
      updatingSubtitle: 'Keep the app open for live tracking',
      offlineTitle: 'You are offline',
      offlineSubtitle: 'Go online to receive jobs and share location',
      offlineAction: 'Go Online',
      liveBadge: 'Live',
      distanceAwaySuffix: 'away',
      selectorTitle: 'Select how you are travelling',
      selectorSubtitle: 'Customers will see this mode on your live location card.',
      locationAccessTitle: 'Location access needed',
      locationAccessSubtitle: 'Enable location to share your live position with the customer.',
      locationAccessButton: 'Enable Location',
      modeWalkLabel: 'Walk',
      modeBikeLabel: 'Bike',
      modeCarLabel: 'Car',
      workerMarkerTitle: 'Worker live location',
      destinationMarkerTitle: 'Service address',
      mapUnavailableTitle: 'Map is unavailable',
      mapUnavailableSubtitle: 'Add the Google Maps API key and rebuild the app to view route map.',
      readerUnavailable: 'Live location is unavailable in this build. Reinstall the latest app or contact support.',
    },
    tabs: {
      all: 'All',
      newJobs: 'New Jobs',
      completed: 'Completed',
    },
    detailsTitle: 'Job Details',
    detailsNotesLabel: 'Notes',
    detailsLoadError: 'Unable to load job details right now.',
    retryAction: 'Retry',
    tryAgainDescription: 'Please try again.',
    acceptEnRouteSyncInfo: 'Job accepted, but we could not mark you en route yet.',
    detailsSubtitle: 'Fetch details from backend by job id.',
    startOtpTitle: 'Start Job Verification',
    startOtpSubtitle: 'Ask the customer for the 4-digit OTP to start the job.',
    startOtpNote: 'You can start the job only after verifying OTP.',
    startOtpInputLabel: 'Start OTP',
    startOtpInputPlaceholder: 'Enter 4-digit OTP',
    startOtpButton: 'Start Job',
    startOtpInvalidLength: 'Enter a valid 4-digit OTP.',
    routeTitle: 'Route to booking',
    routeReading: 'Calculating road route',
    routeFallback: 'Route unavailable, showing approximate path.',
    routeWaiting: 'Waiting for route details.',
    liveLocationNotReadyTitle: 'Live location not ready',
    liveLocationNotReadySubtitle: 'This tab becomes active once the booking is confirmed and tracking is available.',
    liveLocationUnavailableTitle: 'Live location unavailable',
    liveLocationUnavailableSubtitle: 'Tracking data has not arrived yet. We will show it when the booking goes live.',
    openInMaps: 'Open in Google Maps',
    cancelAction: 'Cancel Job',
    cancelCardTitle: 'Need to cancel this job?',
    cancelCardSubtitle: 'You can cancel only before OTP verification.',
    cancelConfirmTitle: 'Cancel this job?',
    cancelConfirmSubtitle: 'You can cancel only before OTP start. Backend may reopen worker search for the customer.',
    cancelConfirmButton: 'Cancel Job',
    progressTitle: 'Job Progress',
    progressSubtitle: 'Update your actual progress. Backend will confirm the allowed transition.',
    progressEnRoute: 'En Route',
    progressArrived: 'Arrived',
    progressComplete: 'Complete Work',
    progressArrivedHint: 'Mark this after you reach the customer location.',
    progressCompleteHint: 'Use this after finishing the service. The customer will confirm work completion before payment recording.',
    progressCompleteConfirmTitle: 'Complete this work?',
    progressCompleteConfirmSubtitle: 'This tells the backend the service work is complete. Payment can be recorded after the customer confirms completion.',
    progressCompleteConfirmButton: 'Complete Work',
    paymentDetailsTitle: 'Payment Details',
    paymentSummaryTitle: 'Payment summary',
    paymentBillAmountLabel: 'Bill amount',
    paymentAmountReceivedLabel: 'Amount received',
    billSummaryTitle: 'Bill Summary',
    billSubtotalLabel: 'Subtotal',
    billPlatformFeeLabel: 'Platform fee',
    billPlatformFeeHint: 'Helps us run the platform',
    billTaxLabel: 'Tax',
    billDiscountLabel: 'Discount',
    billBookingTotalLabel: 'Booking total',
    billTotalLabel: 'Total',
    billCommissionLabel: 'Dellite commission',
    billCommissionHint: 'Commission on service charges only.',
    billTipHint: 'Tip goes 100% to you.',
    serviceTabDurationLabel: 'Duration',
    serviceTabQuantityLabel: 'Quantity',
    serviceTabSelectedTitle: 'Selected services',
    billCustomerBillLabel: 'Customer bill',
    billCustomerPayableLabel: 'Customer pays you',
    paymentReceivedMoneyTitle: 'Received money',
    paymentReceivedMoneySubtitle: 'Choose how you received the payment.',
    paymentReceivedMoneyReadySubtitle: 'Customer has marked the work completed. Record whether you received cash or UPI.',
    paymentReceivedCustomerPending: 'Ask the customer to tap Mark work completed first. After that, you can record the cash or UPI amount here.',
    paymentReceivedMoneyAction: 'Received money',
    paymentReceivedMoneySheetHint: 'Select the payment mode that matches what the customer used.',
    paymentReceivedCash: 'Received Cash',
    paymentReceivedUpi: 'Received UPI',
    paymentAmountLabel: 'Amount',
    paymentStatusLabel: 'Payment status',
    paymentModeLabel: 'Payment mode',
    paymentPaidAmountLabel: 'Paid amount',
    paymentPayableAmountLabel: 'Payable amount',
    paymentPaidAtLabel: 'Paid at',
    paymentPendingLabel: 'Pending',
    paymentTransactionCompletedLabel: 'Transaction Completed',
    paymentTransactionPendingLabel: 'Transaction Pending',
    paymentTipLabel: 'Customer tip',
    paymentWorkerEarningLabel: 'Your earning',
    paymentCommissionDueLabel: 'Commission due',
    workerPayoutLabel: 'Your Earning',
    payoutShownAfterRefresh: 'Shown after refresh',
    callCustomerAction: 'Call',
    contactEventError: 'Could not save contact history.',
  },
  earnings: {
    titlePrefix: 'My',
    title: 'Earnings',
    subtitle: 'Track payouts, commission due, and booking-wise settlement.',
    periodToday: 'Today',
    periodThisMonth: 'This Month',
    periodThisYear: 'This Year',
    periodTodayDescription: 'Settlements completed today',
    periodThisMonthDescription: 'Settlements from the current month',
    periodThisYearDescription: 'Settlements from the current year',
    periodFilterSheetSubtitle: 'Choose which settlement period to view',
    jobSingularSuffix: 'Job',
    periodCustom: 'Custom',
    growthFallback: '--',
    growthNoChange: 'No change',
    growthVsYesterdaySuffix: 'vs yesterday',
    growthVsLastMonthSuffix: 'vs last month',
    growthVsLastYearSuffix: 'vs last year',
    growthVsPreviousRangeSuffix: 'vs previous range',
    netEarningsLabel: 'Net Earnings',
    netEarningsCaption: 'All-time after settlements and commission',
    periodNetEarningsCaption: 'Net earnings in selected period',
    summaryTabLabel: 'Summary',
    settlementsTabLabel: 'Settlements',
    filterByPeriodTitle: 'Filter by period',
    filterAction: 'Filter',
    periodFilterCancelAction: 'Cancel',
    periodFilterApplyAction: 'Apply',
    commissionDueBannerTitle: 'You owe Dellite',
    commissionDueBannerDescription: 'Pay commission for cash or UPI jobs.',
    commissionDuePayNowAction: 'Pay now',
    commissionPaySheetTitle: 'Pay commission',
    commissionPaySheetSubtitle: 'Choose how you want to pay your commission due.',
    commissionPaySheetAmountLabel: 'Amount due',
    commissionPayPhonePeLabel: 'PhonePe',
    commissionPayPhonePeSubtitle: 'Pay securely with PhonePe UPI.',
    commissionPayPhonePeComingSoon: 'PhonePe checkout will be available soon.',
    commissionPayRazorpayLabel: 'Razorpay',
    commissionPayRazorpaySubtitle: 'Pay with cards, UPI, or wallets via Razorpay.',
    commissionPayComingSoonBadge: 'Coming soon',
    commissionPaySelectAction: 'Pay',
    commissionPaymentProcessing: "Payment processing — we'll update shortly.",
    commissionPaymentCancelled: 'Payment cancelled.',
    commissionPaymentFailed: 'Payment could not be completed. Please try again.',
    commissionPaymentRefreshing: 'Confirming payment...',
    settlementPayCommissionAction: 'Pay for this day',
    completedJobsLabel: 'Completed Jobs',
    averagePerJobLabel: 'Avg / Job',
    readyForPayoutTitle: 'Ready for Payout',
    readyForPayoutHelper: 'Ready to send to your bank or UPI.',
    commissionDueTitle: 'You owe Dellite',
    commissionDueHelper: 'Commission for cash or worker UPI jobs.',
    payoutInProcessTitle: 'Payout in Process',
    payoutInProcessHelper: 'Already picked for payout and being processed.',
    totalPaidByDelliteTitle: 'Total Paid by Dellite',
    totalPaidByDelliteHelper: 'Total amount Dellite has paid you so far.',
    dailySettlementTitle: 'Daily Settlement',
    dailySettlementBadge: 'Processed once per day',
    dailySettlementDescription: 'Eligible payouts are settled daily. Cash or worker UPI jobs may create commission due if you collected payment directly.',
    dailySettlementsTitle: 'Settlements',
    dailySettlementsSubtitle: 'Day-level settlement history for completed jobs.',
    viewAllAction: 'View all',
    onlineModeLabel: 'Online',
    cashModeLabel: 'Cash',
    upiModeLabel: 'UPI',
    totalBillLabel: 'Total Bill',
    yourEarningLabel: 'Your Earning',
    netSettlementLabel: 'Net Settlement',
    jobsSuffix: 'Jobs',
    dellitePaysPrefix: 'Dellite Pays',
    youPayDellitePrefix: 'You Pay Dellite',
    settledLabel: 'Settled',
    retryErrorTitle: 'Unable to load earnings. Please try again.',
    availableBalance: 'Available Balance',
    commissionDueBalance: 'Commission Due',
    refreshAction: 'Refresh',
    loadMoreAction: 'Load more settlements',
    settlementListTitle: 'Booking settlements',
    settlementListSubtitle: 'Completed jobs and payout progress from backend.',
    helperFallback: 'Daily settlement means Dellite settles eligible earnings once every day.',
    windowFallback: 'Processed once per day',
    loadError: 'Unable to load earnings right now.',
    ledgerTab: 'Ledger',
    earningsTab: 'Earnings',
    commissionDuesTab: 'Commission',
    payoutsTab: 'Payouts',
    emptyLedgerTitle: 'No wallet ledger yet',
    emptyLedgerDescription: 'Wallet entries will appear after completed payments, dues, or payouts.',
    emptyEarningsTitle: 'No earnings yet',
    emptyEarningsDescription: 'Completed booking payments will create earning rows here.',
    emptyCommissionTitle: 'No commission dues',
    emptyCommissionDescription: 'Commission dues will appear here after backend creates them.',
    emptyPayoutsTitle: 'No payouts yet',
    emptyPayoutsDescription: 'Payout history will appear here when payouts are created.',
    bookingCodeFallback: 'No booking code',
    referenceFallback: 'No reference',
    createdAtFallback: 'Date unavailable',
    grossLabel: 'Gross',
    tipLabel: 'Tip',
    commissionLabel: 'Commission',
    carriedForwardLabel: 'Carried forward commission settled',
    jobsCompletedOnLabel: 'Jobs completed',
    netLabel: 'Net',
    statusCommissionDue: 'Commission Due',
    statusDraft: 'Draft',
    statusReady: 'Ready',
    statusProcessing: 'Processing',
    statusPaid: 'Paid',
    statusSettled: 'Settled',
    emptyTodaySettlementTitle: 'No settlement for today',
    emptyTodaySettlementDescription: "Today's jobs will be settled tomorrow after 12:05 AM.",
    emptySettlementsTitle: 'No settlements in this period',
    emptySettlementsDescription: 'Settled days will appear here after daily settlement runs.',
    settlementDetailTitle: 'Settlement Detail',
    settlementDetailSubtitle: 'Daily settlement breakdown for completed jobs',
    payableAmountLabel: 'Payable',
    paidAmountLabel: 'Paid Amount',
    jobsInSettlementTitle: 'Jobs in this settlement',
    jobsBreakdownUnavailable: 'Job breakdown unavailable',
    settlementTabPayout: 'Payout',
    settlementTabJobs: 'Jobs',
    settlementPayoutEmptyTitle: 'No payout details yet',
    settlementPayoutEmptyDescription: 'Payout or commission details will appear here once available.',
    explanationWorkerPays: 'You collected payment directly (cash/UPI). Dellite commission for these jobs is due.',
    explanationDellitePays: 'After commission adjustment, Dellite pays this net amount to you.',
    explanationCarriedForward: "Commission from earlier cash/UPI days was settled in this day's net calculation.",
    commissionStatusDue: 'Due',
    commissionStatusDeducted: 'Deducted',
    commissionStatusPaid: 'Paid',
    commissionStatusWaived: 'Waived',
    commissionStatusNotApplicable: '—',
    carriedForwardHelperPrefix: 'Includes',
    carriedForwardHelperSuffix: 'carried forward from earlier days',
    customDateTitle: 'Select date range',
    customDateStartLabel: 'Start date',
    customDateEndLabel: 'End date',
    customDatePlaceholder: 'YYYY-MM-DD',
    customDateApplyAction: 'Apply',
    customDateCancelAction: 'Cancel',
    customDateInvalidFormat: 'Enter dates in YYYY-MM-DD format.',
    customDateRangeInvalid: 'Start date must be on or before end date.',
    paymentMixLabel: 'Payment mix',
    dueLabel: 'Due',
    paidLabel: 'Paid',
    remainingLabel: 'Remaining',
    payoutMethodFallback: 'Payout method pending',
    payoutSectionTitle: 'Payout',
    payoutStatusPendingTitle: 'Payout scheduled',
    payoutStatusPendingSubtitle: 'Waiting for the next payout run.',
    payoutStatusProcessingTitle: 'Payout in progress',
    payoutStatusProcessingSubtitle: 'Your payout is being processed by the provider.',
    payoutStatusPaidTitle: 'Paid',
    payoutStatusFailedTitle: 'Payout failed',
    payoutStatusFailedHint: 'Please retry or contact support if this continues.',
    payoutStatusBlockedTitle: 'Action needed',
    payoutStatusBlockedBankInfo: 'Add your bank or UPI details to receive payouts.',
    payoutGrossLabel: 'Gross',
    payoutAdjustedLabel: 'Adjusted',
    payoutNetPaidLabel: 'Net paid',
    payoutProviderLabel: 'Provider',
    payoutPaidOnLabel: 'Paid on',
    payoutPaidToLabel: 'Paid to',
    payoutUtrLabel: 'UTR / Reference No.',
    payoutUtrHelper: 'Use this UTR to verify the payment in your bank/UPI app.',
    payoutTransactionIdLabel: 'Transaction ID',
    payoutUtrCopyAction: 'Copy',
    payoutUtrCopySuccess: 'UTR copied',
    payoutMethodUpi: 'UPI',
    payoutMethodBank: 'Bank',
    payoutAddDetailsAction: 'Add payout details',
    commissionDueSummaryTitle: 'You owe Dellite',
    commissionRecoveredLabel: 'Commission recovered',
    carriedForwardDueLabel: 'Carried forward due',
  },
  profile: {
    title: 'Profile',
    roleLabel: 'Worker',
    memberSincePrefix: 'Member since',
    phoneLabel: 'Phone:',
    nameLabel: 'Name:',
    emailLabel: 'Email',
    contactInfoTitle: 'Contact Info',
    phoneFallback: 'Not available',
    nameFallback: 'Not set',
    notProvided: 'Not provided',
    editProfileButton: 'Edit Profile',
    payoutDetailsButton: 'Payout Details',
      bankInfoButton: 'Bank Account Info',
      allJobsButton: 'All Jobs',
      allJobsSubtitle: 'View all jobs with status filters',
    allSkillsButton: 'All Skills',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Profile preferences',
    settings: {
      title: 'Settings',
      subtitle: 'Manage worker app preferences and job controls.',
      notificationsTitle: 'Notifications',
      notificationsSubtitle: 'Control job requests, payments, and account alerts.',
      locationTitle: 'Location sharing',
      locationSubtitle: 'Manage live location access for accepted jobs.',
      securityTitle: 'Security',
      securitySubtitle: 'Review session and device safety settings.',
    },
    helpTitle: 'Help & Support',
    helpSubtitle: 'Get support and report issues',
    notificationsTitle: 'Notifications',
    notificationsSubtitle: 'Job requests, payments, and account alerts',
    logoutTitle: 'Logout',
    logoutSubtitle: 'Sign out from this device',
    logoutConfirmTitle: 'Log out now?',
    logoutConfirmSubtitle: 'You will be signed out from this device.',
    helpSupportButton: 'Help & Support',
    logoutButton: 'Logout',
    edit: {
      step: 'UPDATE PROFILE',
      titlePrefix: 'Update your',
      titleGradientWord: 'profile',
      subtitle: 'Keep your details accurate for better trust and job matching.',
      title: 'Edit Profile',
      fullNamePlaceholder: 'Full Name',
      emailPlaceholder: 'Email Address',
      saveButton: 'Save Changes',
    },
    payout: {
      title: 'Bank Account Info',
      subtitle: 'Add payout details using UPI or bank account.',
      verifyPromptTitle: "Verify it's you",
      verifyPromptSubtitle: 'Use your phone lock to view payout details.',
      verifyPromptCancel: 'Cancel',
      lockedTitle: 'Payout details locked',
      lockedSubtitle: 'Verify with your phone lock to view sensitive payout information.',
      lockedButton: 'Unlock',
      phoneLockRequiredTitle: 'Phone lock required',
      phoneLockRequiredSubtitle: 'Please enable screen lock on your phone to protect payout information.',
      phoneLockRequiredButton: 'Try again',
      methodTypeLabel: 'Payout Method',
      upiOption: 'UPI',
      bankOption: 'Bank Account',
      upiLabel: 'UPI ID',
      upiPlaceholder: 'name@bank',
      accountHolderLabel: 'Account Holder Name',
      accountHolderPlaceholder: 'Full name as per bank account',
      accountLabel: 'Bank Account Number',
      accountPlaceholder: 'Enter bank account number',
      ifscLabel: 'IFSC Code',
      ifscPlaceholder: 'SBIN0001234',
      fetchError: 'Unable to load bank info.',
      createButton: 'Save Bank Info',
      updateButton: 'Update Bank Info',
      upiHint: 'Use a valid UPI ID linked to your active bank account.',
      bankHint: 'Enter accurate account number and IFSC to avoid payout failures.',
      updatedAtPrefix: 'Last updated: ',
      upiRequired: 'UPI ID is required',
      accountHolderRequired: 'Account holder name is required',
      accountRequired: 'Bank account number is required',
      ifscRequired: 'IFSC code is required',
    },
    helpSupport: {
      title: 'Help & Support',
      subtitle: 'Support chat, FAQs, and contact channels can be added here.',
    },
    identityVerification: {
      title: 'Identity Verification',
      subtitle: 'View Aadhaar verification status and uploaded files.',
      menuTitle: 'Identity Verification',
      menuSubtitle: 'Check Aadhaar front/back and current status',
      step: 'PROFILE VERIFICATION',
      titlePrefix: 'Profile',
      titleHighlight: 'Verification',
      aadhaarFrontTitle: 'Aadhaar Front',
      aadhaarBackTitle: 'Aadhaar Back',
      noFile: 'File not uploaded yet.',
      statusLabel: 'Status',
      rejectedHint: 'Your previous Aadhaar upload was rejected. Re-upload clear images to continue.',
      uploadButton: 'Upload Documents',
      maxFileHint: 'PNG, JPG only - Max 5MB',
    },
    allSkills: {
      title: 'All Skills',
      titlePrefix: 'All',
      titleHighlight: 'Skills',
      subtitle: 'View your registered skills and approval status.',
      addSkillButton: 'Add Skill',
      activeLabel: 'Available',
      inactiveLabel: 'Unavailable',
      addCertificateButton: 'Add Certificate',
      certificateRequiredLabel: 'Certificate required to unlock bookings.',
      certificatePendingLabel: 'Waiting for certificate approval.',
      certificateApprovedLabel: 'Certificate approved.',
      noCertificateRequiredLabel: 'No certificate required for this skill.',
    },
    certificates: {
      menuTitle: 'Certificates',
      menuSubtitle: 'Upload and review skill certificates',
      titlePrefix: 'Manage',
      titleHighlight: 'Certificates',
      subtitle: 'Add or review certificates linked with your skills.',
      saveButton: 'Save Certificates',
      addSkillButton: 'Add Skill',
      emptyState: 'No certificate is currently required for your skills.',
      emptyDescription: 'Add a new skill to see certificate requirements.',
      waitingTitle: 'Waiting for approval',
      waitingSubtitle: 'Certificates are submitted and currently under review.',
      loadErrorTitle: 'Could not load certificates',
      loadErrorDescription: 'Pull to refresh or tap retry.',
      card: {
        actionNeededBadge: 'Upload needed',
        pendingBadge: 'Under review',
        approvedBadge: 'Verified',
        neededForLabel: 'This unlocks',
        stepTypeTitle: 'What type is this?',
        stepTypeHint: 'Pick the document type that matches your certificate.',
        typeRequiredHint: 'Please choose a certificate type to continue.',
        selectedTypeLabel: 'Selected',
        stepUploadTitle: 'Add your certificate',
        stepUploadHint: 'Use a clear photo or PDF so we can verify it quickly.',
        uploadIdleTitle: 'Tap to upload certificate',
        uploadPickingTitle: 'Opening files...',
        uploadDescription: 'Photo from gallery or PDF file',
        uploadHelper: 'PDF · JPG · PNG · up to 5MB',
        uploadChangeTitle: 'Change certificate',
        uploadReadyTitle: 'Certificate ready',
        uploadReadySubtitle: 'Looks good. Tap to change anytime before you save.',
        uploadCtaLabel: 'Choose file',
        formatsLabel: 'Accepted',
        maxSizeLabel: 'Max 5MB',
        progressTypeLabel: 'Type',
        progressFileLabel: 'File',
        verifiedTitle: 'Certificate verified',
        verifiedSubtitle: 'Approved. You can take related jobs once skills are ready.',
        pendingTitle: 'Sent for verification',
        pendingSubtitle: 'Our team is checking this. You will be notified when it is approved.',
        fallbackTitle: 'Certificate',
      },
    },
    skillManager: {
      addTitlePrefix: 'Add',
      titleHighlight: 'Skills',
      addSubtitle: 'Select and add new skills to your profile.',
      backToSelectionButton: 'Back to Selection',
      addMoreTitle: 'Add more services',
      addMoreSubtitle: 'Existing skills are marked Added. Use All Skills to turn availability on or off.',
      loadErrorTitle: 'Could not load skills',
      loadErrorDescription: 'Pull to refresh or tap retry.',
      emptyServicesTitle: 'No services available',
      emptyServicesDescription: 'Please try again after refreshing.',
      selectedCountLabel: 'selected',
      selectedLabel: 'Selected',
      removeSelectedHint: 'Tap a chip to remove',
      addedLabel: 'Added',
      addSkillLabel: 'Add skill',
      selectAllButton: 'Select all',
      servicesCountSuffix: 'services',
      certificateRequiredLabel: 'Certificate Required',
      autoApprovalLabel: 'Auto approval',
    },
    referral: {
      title: 'Referral',
      menuTitle: 'Referral Program',
      menuSubtitle: 'View code and reward details',
      pageTitle: 'Refer & Earn',
      pageSubtitle: 'Invite friends and earn rewards',
      heroTitle: 'Refer & Earn',
      heroSubtitle: 'Share the love, earn rewards!',
      conversionSubtitle: 'Redeem coins for real value',
      howItWorksTitle: 'How it works',
      inviteCustomerTitle: 'Invite a Customer',
      inviteWorkerTitle: 'Invite a Worker',
      youLabelPrefix: 'YOU',
      newCustomerLabel: 'NEW CUSTOMER',
      newWorkerLabel: 'NEW WORKER',
      andLabel: 'AND',
      worthPrefix: 'Worth',
      signupLabel: 'On signup',
      triggerPillPrefix: 'On',
      shareButton: 'Share with Friends',
      codeLabel: 'Your Referral Code',
      codeFallback: 'Not available',
      copyButton: 'Copy Code',
      copySuccess: 'Referral code copied',
      infoTitle: 'How it works',
      infoText: 'Share this code with friends. Rewards are applied based on whether they join as customer or worker.',
      rewardsTitle: 'Reward Breakdown',
      rewardCustomerLabel: 'When referred user joins as CUSTOMER',
      rewardWorkerLabel: 'When referred user joins as WORKER',
      rewardUnavailable: 'Reward details will appear here soon.',
      bothRolesRuleTitle: 'Both Roles Rule',
    },
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Stay updated with job requests, payments, and account activity.',
    markAllRead: 'Mark all as read',
    allRead: 'You are all caught up',
    unreadCountLabel: 'unread',
    emptyTitle: 'No notifications yet',
    emptyDescription: 'Important job and account updates will appear here.',
    errorTitle: 'Unable to load notifications',
    deleteAction: 'Delete',
    loadingMore: 'Loading more updates...',
    loadMoreAction: 'Load more',
    viewAction: 'View',
  },
  ratings: {
    customerSheetTitle: 'Rate your partner',
    customerSheetSubtitle: 'Share how the service went. Your feedback helps us improve Dellite.',
    workerSheetTitle: 'Rate this customer',
    workerSheetSubtitle: 'Share how the booking went. Your feedback helps us improve Dellite.',
    reviewLabel: 'Review (optional)',
    reviewPlaceholder: 'Write a short review',
    submitButton: 'Submit Rating',
    requiredError: 'Please choose a rating.',
    reviewMaxError: 'Review must be 500 characters or less.',
    submitError: 'Unable to submit rating right now.',
    successToast: 'Rating submitted successfully.',
  },
  bottomSheet: {
    closeButton: 'Close',
    cancelButton: 'Cancel',
  },
} as const;
