export const APP_TEXT = {
  auth: {
    loginTitle: 'Welcome to Dellite',
    loginSubtitle: 'Continue with your phone number.',
    otpTitle: 'Verify your phone',
    otpSubtitle: 'Enter the code we sent to continue.',
    otpVerification: {
      title: 'Verify OTP',
      codeSentPrefix: 'Code sent to ',
      verifyButton: 'Verify OTP',
      helpText: 'Did not receive code? Wait for timer and resend.',
    },
    phoneLogin: {
      title: 'Home services, simplified.',
      subtitle:
        'Book trusted professionals for any job from plumbing to cleaning, all at your fingertips.',
      countryCode: 'IN +91',
      phonePlaceholder: 'Enter your 10-digit phone number',
      sendOtpButton: 'Send OTP',
      securePrivate: 'Secure & private',
      noSpam: 'No spam calls',
      terms: 'By continuing, you agree to our Terms of Service & Privacy Policy.',
    },
  },
  onboarding: {
    title: 'Let us know your name',
    subtitle: 'Set up your profile in one quick step.',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    submit: 'Complete Setup',
    identity: {
      step: 'STEP 1 OF 2',
      titlePrefix: 'Tell us about',
      gradientWord: 'yourself',
      subtitle: "We'll personalize your experience based on this info",
      uploadPhotoTitle: 'Add your photo',
      uploadPhotoSubtitle: 'This helps workers identify you quickly',
      firstNameLabel: 'First Name',
      firstNamePlaceholder: 'Enter your first name',
      lastNameLabel: 'Last Name',
      lastNamePlaceholder: 'Enter your last name',
      emailLabel: 'Email Address',
      emailPlaceholder: 'Enter your email address',
      referralLabel: 'Referral Code (Optional)',
      referralPlaceholder: 'Enter referral code',
      genderLabel: 'Gender',
      nextButton: 'Continue',
    },
    welcome: {
      step: 'STEP 2 OF 2',
      titlePrefix: 'Welcome',
      titleGradientWord: 'Aboard!',
      subtitle: 'Your account is ready. Book services instantly!',
      cta: 'Explore Services',
      benefits: {
        trustedProfessionals: 'Book trusted professionals',
        verifiedWorkers: 'Verified & rated workers',
        transparentPricing: 'Transparent pricing always',
      },
    },
  },
  main: {
    homeTitle: 'Home',
    ongoingTitle: 'Ongoing',
    bookingsTitle: 'Bookings',
    profileTitle: 'Profile',
  },
  profile: {
    nameFallback: 'Dellite Customer',
    phoneFallback: 'Not provided',
    roleLabel: 'Customer',
    memberSincePrefix: 'Member since',
    editProfileButton: 'Edit Profile',
    contactInfoTitle: 'Contact Info',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    notProvided: 'Not provided',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Account preferences',
    helpTitle: 'Help & Support',
    helpSubtitle: 'Get support and report issues',
    logoutTitle: 'Logout',
    logoutSubtitle: 'Sign out from this device',
    edit: {
      step: 'UPDATE PROFILE',
      titlePrefix: 'Update your',
      titleGradientWord: 'profile',
      subtitle: 'Keep your details accurate for better bookings and support.',
      emailPlaceholder: 'Enter your email address',
      saveButton: 'Save Changes',
    },
    stats: {
      bookings: 'Bookings',
      active: 'Active',
      completed: 'Completed',
    },
  },
  tabs: {
    homeLabel: 'Home',
    ongoingLabel: 'Ongoing',
    bookingsLabel: 'Bookings',
    profileLabel: 'Profile',
  },
};
