export const APP_TEXT = {
  network: {
    offlineTitle: 'No internet connection',
    offlineSubtitle: 'Turn on mobile data or Wi-Fi to continue.',
    openSettingsButton: 'Turn On Data or Wi-Fi',
    retryButton: 'Try Again',
    retryStillOffline: 'Still offline. Please turn on internet and try again.',
    retryBackOnline: 'You are back online.',
  },
  auth: {
    loginTitle: 'Welcome to Dellite',
    loginSubtitle: 'Continue with your phone number.',
    otpTitle: 'Verify your phone',
    otpSubtitle: 'Enter the code we sent to continue.',
    otpVerification: {
      title: 'Verify OTP',
      codeSentPrefix: 'Code sent to ',
      verifyButton: 'Verify OTP',
      helpText: 'Did not receive code? Wait for timer and resend.',
    },
    phoneLogin: {
      title: 'Home services, simplified.',
      subtitle:
        'Book trusted professionals for any job from plumbing to cleaning, all at your fingertips.',
      countryCode: 'IN +91',
      phonePlaceholder: 'Enter your 10-digit phone number',
      sendOtpButton: 'Send OTP',
      securePrivate: 'Secure & private',
      noSpam: 'No spam calls',
      terms: 'By continuing, you agree to our Terms of Service & Privacy Policy.',
    },
  },
  onboarding: {
    title: 'Let us know your name',
    subtitle: 'Set up your profile in one quick step.',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    submit: 'Complete Setup',
    identity: {
      step: 'STEP 1 OF 2',
      titlePrefix: 'Tell us about',
      gradientWord: 'yourself',
      subtitle: "We'll personalize your experience based on this info",
      uploadPhotoTitle: 'Add your photo',
      uploadPhotoSubtitle: 'This helps workers identify you quickly',
      firstNameLabel: 'First Name',
      firstNamePlaceholder: 'Enter your first name',
      lastNameLabel: 'Last Name',
      lastNamePlaceholder: 'Enter your last name',
      emailLabel: 'Email Address',
      emailPlaceholder: 'Enter your email address',
      referralLabel: 'Referral Code (Optional)',
      referralPlaceholder: 'Enter referral code',
      genderLabel: 'Gender',
      nextButton: 'Continue',
    },
    welcome: {
      step: 'STEP 2 OF 2',
      titlePrefix: 'Welcome',
      titleGradientWord: 'Aboard!',
      subtitle: 'Your account is ready. Book services instantly!',
      cta: 'Explore Services',
      notifications: {
        titlePrefix: 'Turn on',
        titleGradientWord: 'notifications',
        subtitle: 'Get booking updates, reminders, and live status changes.',
        actionLabel: 'Enable notifications',
        deniedActionLabel: 'Open settings',
        helpText: 'You can turn this on later from app settings.',
      },
      benefits: {
        trustedProfessionals: 'Book trusted professionals',
        verifiedWorkers: 'Verified & rated workers',
        transparentPricing: 'Transparent pricing always',
      },
    },
  },
  main: {
    homeTitle: 'Home',
    homeOngoing: {
      title: 'Active bookings',
      subtitle: 'Tap any card to track worker, status, and payment.',
    },
    allServicesTitle: 'All Services',
    bookingsTitle: 'Bookings',
    locationAccess: {
      title: 'Allow location access',
      subtitle: 'We use your location to show nearby services and city availability.',
      actionLabel: 'Allow location',
      helpText: 'You can turn this off later in device settings.',
      noLocationLabel: 'No Location',
      locatingLabel: 'Locating...',
    },
    bookings: {
      titlePrefix: 'My',
      titleHighlight: 'Bookings',
      subtitle: 'Check ongoing and completed bookings in one place.',
      ongoingTitle: 'Ongoing bookings',
      allTitle: 'Bookings',
      emptyTitle: 'No bookings found',
      emptyDescription: "You don't have any bookings in this category yet.",
      completedEmptyTitle: 'No completed bookings',
      completedEmptyDescription: 'Finished bookings will appear here.',
      ongoingEmptyTitle: 'No ongoing bookings',
      ongoingEmptyDescription: 'Confirmed and in-progress bookings will appear here.',
      cardBookingStatusLabel: 'Booking Status',
      cardInviteStatusLabel: 'Invite Status',
      cardBookingCodeLabel: 'Booking Code',
      schedulePendingLabel: 'Schedule pending',
      cardTotalBillLabel: 'Total Bill',
      cardPaymentStatusLabel: 'Payment Status',
      cardViewAction: 'View Booking',
      liveLocation: {
        movingTitle: 'On the way',
        movingSubtitleFallback: 'Arriving soon',
        stationaryTitle: 'Stopped for a moment',
        stationarySubtitle: 'Location will update soon',
        weakTitle: 'Location signal weak',
        weakSubtitle: 'Location may update slowly',
        updatingTitle: 'Location updating',
        updatingSubtitle: 'Please check again in a moment',
        offlineTitle: 'Location not live',
        offlineSubtitle: 'Worker location is currently unavailable',
        liveBadge: 'Live',
        distanceAwaySuffix: 'away',
        readingLabel: 'Reading live location',
        workerMarkerTitle: 'Worker live location',
        destinationMarkerTitle: 'Service address',
        mapUnavailableTitle: 'Map is unavailable',
        mapUnavailableSubtitle: 'Add the Google Maps API key and rebuild the app to view live route.',
        readerUnavailable: 'Live location is unavailable in this build. Reinstall the latest app or contact support.',
      },
      tabs: {
        all: 'All',
        ongoing: 'Ongoing',
        completed: 'Completed',
      },
      detailsTitle: 'Booking Details',
      detailsLoadError: 'Unable to load booking details right now.',
      retryAction: 'Retry',
      tryAgainDescription: 'Please try again.',
      detailsSubtitle: 'Review service, worker, schedule, address, and payment details.',
      detailsReferenceLabel: 'Booking ID',
      detailsServiceLabel: 'Service',
      detailsWorkerLabel: 'Worker',
      detailsStatusLabel: 'Status',
      detailsScheduleLabel: 'Schedule',
      detailsAddressLabel: 'Address',
      detailsAmountLabel: 'Amount',
      detailsUnavailable: 'Booking details are unavailable right now.',
      detailsWorkerRole: 'Assigned worker',
      detailsWorkerPending: 'Worker not assigned yet',
      detailsWorkerPendingSubtitle: 'Worker profile and phone details will appear here after acceptance.',
      detailsPayNow: 'Pay now',
      detailsPaymentComingSoon: 'Payment will be available soon.',
      detailsRouteFallback: 'Route unavailable, showing approximate path.',
      startOtpTitle: 'Start Job OTP',
      startOtpSubtitle: 'Share this 4-digit OTP with the worker to start the job.',
      startOtpNote: 'Only share this code when the worker arrives.',
      startOtpRefreshButton: 'Refresh OTP',
      editTitle: 'Edit Booking',
      editSubtitle: 'You can increase service quantity or duration before work starts. Services cannot be removed here.',
      editLoadError: 'Unable to load editable booking details.',
      editScheduleTitle: 'Schedule and notes',
      editSchedulePlaceholder: 'ISO date/time from backend',
      editIncreaseQuantity: '+ Quantity',
      editIncreaseDuration: '+ 30 min',
      editSaveButton: 'Update Booking',
      editAction: 'Edit Booking',
      editLineReadOnlyReason: 'This service line is missing its backend line id, so it cannot be edited safely.',
      cancelAction: 'Cancel Booking',
      cancelCardTitle: 'Need to cancel this booking?',
      cancelCardSubtitle: 'You can cancel only before work starts.',
      cancelConfirmTitle: 'Cancel this booking?',
      cancelConfirmSubtitle: 'This can be done only before work starts. If a worker already accepted, they will be notified.',
      cancelConfirmButton: 'Cancel Booking',
      cancelError: 'Unable to cancel booking.',
      workCompletionAction: 'Mark work completed',
      workCompletionPrompt: 'Work completed?',
      workCompletionConfirmTitle: 'Mark work completed?',
      workCompletionConfirmSubtitle: 'This will complete the booking and ask the partner to confirm payment received.',
      workCompletionConfirmButton: 'Mark Completed',
      workCompletionError: 'Unable to mark work completed.',
      workCompletionPendingPayment: 'Waiting for partner to confirm payment received.',
      paymentDetailsTitle: 'Payment Details',
      paymentSummaryTitle: 'Payment summary',
      paymentBillAmountLabel: 'Bill amount',
      paymentAmountReceivedLabel: 'Amount received',
      paymentTotalAmountLabel: 'Total amount',
      paymentStatusLabel: 'Payment status',
      paymentModeLabel: 'Payment mode',
      paymentPaidAmountLabel: 'Paid amount',
      paymentPayableAmountLabel: 'Payable amount',
      paymentPaidAtLabel: 'Paid at',
      paymentPendingLabel: 'Pending',
      paymentTransactionCompletedLabel: 'Transaction Completed',
      paymentTransactionPendingLabel: 'Transaction Pending',
      paymentDetailsEmptyTitle: 'Payment not ready',
      paymentDetailsEmptyDescription: 'Payment information will appear after work completion.',
      editUnavailableTitle: 'Booking can no longer be edited',
      editUnavailableDescription: 'Editing is only available before work starts on the booking.',
      addTipAction: 'Add tip',
      editTipAction: 'Edit tip',
      removeTipAction: 'Remove tip',
      tipAddedLabel: 'Tip added',
      tipAvailableLabel: 'Tip available until payment is recorded',
      tipUpdateError: 'Unable to update tip right now.',
      tipSheetTitle: 'Add a tip',
      tipSheetSubtitle: 'Choose a preset amount for your partner.',
      tipSelectedPrefix: 'Tip selected',
      paymentModeCash: 'Cash paid to worker',
      paymentModeUpi: 'UPI paid to worker',
      paymentAmountLabel: 'Amount paid',
      paymentTipLabel: 'Tip amount (optional)',
      paymentTipSummaryHint: 'Optional gratitude for your worker. Not included in bill amount.',
      paymentReferenceLabel: 'Reference (optional)',
      paymentSubmitClaim: 'Submit Payment Claim',
      paymentOnlineSaveBadge: 'Save {amount} by paying online',
      paymentOnlineSavingsLine: 'You save {amount} online',
      paymentOnlineOffersLabel: 'Available offers',
      paymentOnlineDiscountBadge: '{amount} off on online payment',
      paymentOnlinePayCta: 'Pay {amount}',
      paymentOnlinePayNowCta: 'Pay now',
      paymentOnlineSheetTitle: 'Pay online',
      paymentOnlineSheetSubtitle: 'Choose how you want to pay securely.',
      paymentOnlineSheetAmountLabel: 'Amount to pay',
      paymentOnlinePhonePeLabel: 'PhonePe',
      paymentOnlinePhonePeComingSoon: 'PhonePe checkout will be available soon.',
      paymentOnlineRazorpayLabel: 'Razorpay',
      paymentOnlineRazorpaySubtitle: 'Pay with UPI, cards, or wallets via Razorpay.',
      paymentOnlineComingSoonBadge: 'Coming soon',
      paymentOnlineSelectAction: 'Pay',
      paymentOnlineSectionTitle: 'Pay online',
      paymentOnlineSectionSubtitle: 'UPI, cards and wallets',
      paymentOnlineYouPayLabel: 'You pay online',
      paymentTipSectionTitle: 'Tip your partner',
      paymentTipSectionSubtitle: 'Optional — show appreciation for great service',
      paymentOnlineResumeCta: 'Resume payment',
      paymentOnlineBlockedTitle: 'Online payment unavailable',
      paymentOnlineProcessing: "Payment processing — we'll update shortly.",
      paymentOnlineCancelled: 'Payment cancelled.',
      paymentOnlineFailed: 'Payment could not be completed. Please try again.',
      paymentOnlineRefreshing: 'Confirming payment...',
      paymentWaitingTitle: 'Waiting for worker confirmation',
      paymentPaidTitle: 'Payment complete',
      paymentIssueTitle: 'Payment needs review',
      callWorkerAction: 'Call',
      contactEventError: 'Could not save contact history.',
    },
    profileTitle: 'Profile',
    loadingHome: 'Loading home...',
    loadingLocation: 'Fetching location...',
    homeLoadError: 'Unable to load home data right now.',
    allServices: {
      searchPlaceholder: 'Search for a service...',
      loadingServices: 'Loading services...',
      loadingMore: 'Loading more...',
      loadMoreCta: 'Load more',
      emptyTitle: 'No services found',
      emptySubtitle: 'Try a different keyword.',
      pullToRefreshHint: 'Pull to refresh and try again.',
    },
    bookingFlow: {
      exploreEyebrow: 'BOOK A SERVICE',
      categoryTitle: 'Choose Subcategory',
      categorySubtitle: 'Select one subcategory first, then choose services inside it.',
      serviceTitle: 'Choose Services',
      serviceSubtitle: 'Pick one or more services from this subcategory only.',
      loadingError: 'Unable to load services right now.',
      retry: 'Retry',
      categoriesLabel: 'Categories',
      subcategoryLabel: 'Subcategories',
      servicesLabel: 'Services',
      chooseSubcategoryCta: 'Choose This Subcategory',
      selectedCountSuffix: 'selected',
      noSubcategory: 'No subcategories available.',
      noService: 'No services available in this subcategory yet.',
      continueCta: 'Continue to Booking',
      detailsEyebrow: 'BOOKING DETAILS',
      detailsTitle: 'Booking Details',
      detailsSubtitle: '',
      bookingTypeLabel: 'Booking Type',
      instantBookingLabel: 'Instant Booking',
      instantBookingSubtitle: 'Fast booking using the current time window.',
      scheduledBookingLabel: 'Scheduled Booking',
      scheduledBookingSubtitle: 'Choose your preferred date and start time.',
      instantSummaryLabel: 'Instant',
      scheduledSummaryLabel: 'Scheduled',
      scheduleSectionTitle: 'Schedule',
      dateLabel: 'Date',
      datePlaceholder: 'YYYY-MM-DD',
      timeLabel: 'Time',
      timePlaceholder: 'HH:MM',
      datePickerCta: 'Choose date',
      timePickerCta: 'Choose time',
      instantBookingHint: 'Instant service will be requested right away.',
      selectedServicesTitle: 'Selected Services',
      selectedServicesCountSuffix: 'selected services',
      selectedServicesCountSingular: 'selected service',
      quantityLabel: 'Quantity',
      durationLabel: 'Duration',
      selectDurationTitle: 'Select Duration',
      selectedDurationLabel: 'Selected Duration',
      estimatedTimeLabel: 'Estimated Time',
      fixedDurationBadge: 'Fixed Duration',
      hourlyPriceBadge: 'Hourly',
      fixedPriceBadge: 'Fixed',
      priceOptionsTitle: 'Price Options',
      optionalChargesTitle: 'Optional charges may apply',
      optionalChargesSubtitle: 'Finalized after service only if extra work or parts are needed.',
      subtotalLabel: 'Subtotal',
      lineTotalLabel: 'Total',
      includedTitle: 'What is included',
      excludedTitle: 'Not included',
      tasksNoIncluded: 'No included tasks for this service.',
      tasksNoExcluded: 'No excluded tasks for this service.',
      locationTitle: 'Location',
      locationCurrentTitle: 'Use Current',
      locationCurrentSubtitle: 'Auto-fill your live location and nearby address details.',
      locationManualTitle: 'Pin Manually',
      locationManualSubtitle: 'Add the exact location details yourself.',
      detectedAddressLabel: 'Google Detected',
      detectedAddressSubtitle: 'Use detected address and refine details.',
      pinnedAddressLabel: 'Pinned Manually',
      pinnedAddressSubtitle: 'Manually pin coordinates and full address.',
      addressDetailsTitle: 'Pinned Location Details',
      currentLocationSummaryTitle: 'Current location summary',
      useCurrentLocationCta: 'Use current location',
      refreshingLocationLabel: 'Refreshing...',
      selectOnMapCta: 'Select on map',
      changeLocationCta: 'Change location',
      selectLocationCta: 'Select location',
      locationPickerEyebrow: 'PIN LOCATION',
      locationPickerTitlePrefix: 'Select your',
      locationPickerTitleHighlight: 'location',
      pinLocationEmptyHint: 'Move the map to place the pin and fetch address details.',
      pinLocationFallbackTitle: 'Pinned location',
      pinLocationResolveError: 'Unable to fetch address details for this pinned location.',
      pinLocationMapTitle: 'Pinned location',
      pinLocationResolvingLabel: 'Fetching address',
      pinLocationMapUnavailableTitle: 'Map is unavailable',
      pinLocationMapUnavailableSubtitle: 'Add the Google Maps API key and rebuild the development app to select location on map.',
      addressLine1Label: 'Address Line 1',
      addressLine2Label: 'Address Line 2',
      addressLine2Placeholder: 'Landmark, apartment, floor',
      areaLabel: 'Area / Locality',
      areaPlaceholder: 'Civil Lines',
      districtLabel: 'District / City',
      districtPlaceholder: 'Prayagraj',
      stateFieldLabel: 'State',
      statePlaceholder: 'Uttar Pradesh',
      pincodeLabel: 'Pincode',
      pincodePlaceholder: '211001',
      countryFieldLabel: 'Country',
      countryPlaceholder: 'India',
      latitudeLabel: 'Latitude',
      latitudePlaceholder: '25.4358',
      longitudeLabel: 'Longitude',
      longitudePlaceholder: '81.8463',
      addressPreviewTitle: 'Address Preview',
      addressPreviewPlaceholder: 'Address summary will appear here.',
      invalidCoordinatesHint: 'Add valid coordinates so workers can navigate correctly.',
      currentLocationEmptyHint: 'Current address details will appear here after location refresh.',
      missingPriceSelectionError: 'Select one price option for every chosen service before continuing.',
      invalidScheduleError: 'Enter a valid scheduled date and time.',
      slotLabel: 'Preferred Slot',
      slotMorning: 'Today Morning (9:00 AM - 12:00 PM)',
      slotAfternoon: 'Today Afternoon (12:00 PM - 4:00 PM)',
      slotEvening: 'Today Evening (4:00 PM - 8:00 PM)',
      addressLabel: 'Service Address',
      addressPlaceholder: 'House/Flat, street, landmark',
      notesLabel: 'Notes (Optional)',
      notesSimpleLabel: 'Notes',
      notesPlaceholder: 'Share entry details or specific requests',
      reviewCta: 'Review Booking',
      confirmEyebrow: 'CONFIRM BOOKING',
      confirmTitle: 'Ready to Confirm',
      bookingOverviewTitle: 'Booking Overview',
      summaryCategory: 'Category',
      summarySubcategory: 'Subcategory',
      summaryService: 'Service',
      summaryBookingType: 'Booking Type',
      summarySlot: 'Slot',
      summaryAddress: 'Address',
      summaryNotes: 'Notes',
      billSummaryTitle: 'Bill Summary',
      quoteLoading: 'Calculating final amount...',
      quoteError: 'Unable to calculate final amount. Please try again.',
      quoteSubtotal: 'Subtotal',
      quotePlatformFee: 'Platform fee',
      quotePlatformFeeHint: 'Helps us run the platform',
      quoteTax: 'Tax',
      quoteDiscount: 'Discount',
      quoteTotalPay: 'Total pay',
      quoteApplied: 'Applied',
      quoteCouponAppliedSubtitle: 'Offer auto-applied by Dellite',
      quoteYouSavePrefix: 'You save',
      quoteEstimatedHint: 'Estimated amount. Final charges are confirmed after service completion.',
      possibleAddOnsTitle: 'Possible add-ons',
      quantitySummaryPrefix: 'Quantity',
      statusPrefix: 'Status',
      referencePrefix: 'Ref',
      instantScheduleLabel: 'Instant booking',
      noNotes: 'No notes added',
      confirmCta: 'Confirm Booking',
      doneTitle: 'Booking Confirmed',
      doneSubtitle: 'Your request is submitted and visible in Bookings.',
      doneBookingIdPrefix: 'Booking ID',
      goBookings: 'Go to Bookings',
      backHome: 'Back to Home',
    },
  },
  profile: {
    nameFallback: 'Dellite Customer',
    phoneFallback: 'Not provided',
    roleLabel: 'Customer',
    memberSincePrefix: 'Member since',
    editProfileButton: 'Edit Profile',
    contactInfoTitle: 'Contact Info',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    notProvided: 'Not provided',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Account preferences',
    settings: {
      title: 'Settings',
      subtitle: 'Manage customer app preferences and account controls.',
      notificationsTitle: 'Notifications',
      notificationsSubtitle: 'Control booking updates, offers, and account alerts.',
      locationTitle: 'Location preferences',
      locationSubtitle: 'Manage city, location access, and nearby service availability.',
      securityTitle: 'Security',
      securitySubtitle: 'Review session and device safety settings.',
    },
    helpTitle: 'Help & Support',
    helpSubtitle: 'Get support and report issues',
      notificationsTitle: 'Notifications',
      notificationsSubtitle: 'Booking updates, offers, and account alerts',
      bookingsTitle: 'Bookings',
      bookingsSubtitle: 'View all bookings with status filters',
      logoutTitle: 'Logout',
    logoutSubtitle: 'Sign out from this device',
    logoutConfirmTitle: 'Log out now?',
    logoutConfirmSubtitle: 'You will be signed out from this device.',
    logoutButton: 'Logout',
    edit: {
      step: 'UPDATE PROFILE',
      titlePrefix: 'Update your',
      titleGradientWord: 'profile',
      subtitle: 'Keep your details accurate for better bookings and support.',
      emailPlaceholder: 'Enter your email address',
      saveButton: 'Save Changes',
    },
    stats: {
      bookings: 'Bookings',
      active: 'Active',
      completed: 'Completed',
    },
    referral: {
      title: 'Referral',
      menuTitle: 'Referral Program',
      menuSubtitle: 'View code and reward details',
      pageTitle: 'Refer & Earn',
      pageSubtitle: 'Invite friends and earn rewards',
      heroTitle: 'Refer & Earn',
      heroSubtitle: 'Share the love, earn rewards!',
      conversionSubtitle: 'Redeem coins for real value',
      howItWorksTitle: 'How it works',
      inviteCustomerTitle: 'Invite a Customer',
      inviteWorkerTitle: 'Invite a Worker',
      youLabelPrefix: 'YOU',
      newCustomerLabel: 'NEW CUSTOMER',
      newWorkerLabel: 'NEW WORKER',
      andLabel: 'AND',
      worthPrefix: 'Worth',
      signupLabel: 'On signup',
      triggerPillPrefix: 'On',
      shareButton: 'Share with Friends',
      codeLabel: 'Your Referral Code',
      codeFallback: 'Not available',
      copyButton: 'Copy Code',
      copySuccess: 'Referral code copied',
      infoTitle: 'How it works',
      infoText: 'Share this code with friends. Rewards are applied based on whether they join as customer or worker.',
      rewardsTitle: 'Reward Breakdown',
      rewardCustomerLabel: 'When referred user joins as CUSTOMER',
      rewardWorkerLabel: 'When referred user joins as WORKER',
      rewardUnavailable: 'Reward details will appear here soon.',
      bothRolesRuleTitle: 'Both Roles Rule',
    },
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Stay updated with bookings, payments, and account activity.',
    markAllRead: 'Mark all read',
    allRead: 'All caught up',
    unreadCountLabel: 'Unread',
    emptyTitle: 'No notifications yet',
    emptyDescription: 'Important booking and account updates will appear here.',
    errorTitle: 'Unable to load notifications',
    deleteAction: 'Delete',
    loadingMore: 'Loading more updates...',
    loadMoreAction: 'Load more',
    viewAction: 'View',
  },
  bottomSheet: {
    closeButton: 'Close',
    cancelButton: 'Cancel',
  },
  tabs: {
      homeLabel: 'Home',
      allServicesLabel: 'Services',
      profileLabel: 'Profile',
  },
};
