export const APP_TEXT = {
  auth: {
    loginTitle: 'Welcome to Dellite',
    loginSubtitle: 'Continue with your phone number.',
    otpTitle: 'Verify your phone',
    otpSubtitle: 'Enter the code we sent to continue.',
    otpVerification: {
      title: 'Verify OTP',
      codeSentPrefix: 'Code sent to ',
      verifyButton: 'Verify OTP',
      helpText: 'Did not receive code? Wait for timer and resend.',
    },
    phoneLogin: {
      title: 'Home services, simplified.',
      subtitle:
        'Book trusted professionals for any job from plumbing to cleaning, all at your fingertips.',
      countryCode: 'IN +91',
      phonePlaceholder: 'Enter your 10-digit phone number',
      sendOtpButton: 'Send OTP',
      securePrivate: 'Secure & private',
      noSpam: 'No spam calls',
      terms: 'By continuing, you agree to our Terms of Service & Privacy Policy.',
    },
  },
  onboarding: {
    title: 'Let us know your name',
    subtitle: 'Set up your profile in one quick step.',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    submit: 'Complete Setup',
    identity: {
      step: 'STEP 1 OF 2',
      titlePrefix: 'Tell us about',
      gradientWord: 'yourself',
      subtitle: "We'll personalize your experience based on this info",
      uploadPhotoTitle: 'Add your photo',
      uploadPhotoSubtitle: 'This helps workers identify you quickly',
      firstNameLabel: 'First Name',
      firstNamePlaceholder: 'Enter your first name',
      lastNameLabel: 'Last Name',
      lastNamePlaceholder: 'Enter your last name',
      emailLabel: 'Email Address',
      emailPlaceholder: 'Enter your email address',
      referralLabel: 'Referral Code (Optional)',
      referralPlaceholder: 'Enter referral code',
      genderLabel: 'Gender',
      nextButton: 'Continue',
    },
    welcome: {
      step: 'STEP 2 OF 2',
      titlePrefix: 'Welcome',
      titleGradientWord: 'Aboard!',
      subtitle: 'Your account is ready. Book services instantly!',
      cta: 'Explore Services',
      benefits: {
        trustedProfessionals: 'Book trusted professionals',
        verifiedWorkers: 'Verified & rated workers',
        transparentPricing: 'Transparent pricing always',
      },
    },
  },
  main: {
    homeTitle: 'Home',
    allServicesTitle: 'All Services',
    bookingsTitle: 'Bookings',
    bookings: {
      titlePrefix: 'My',
      titleHighlight: 'Bookings',
      subtitle: 'Check ongoing and completed bookings in one place.',
      tabs: {
        ongoing: 'Ongoing',
        completed: 'Completed',
      },
      detailsTitle: 'Booking Details',
      detailsSubtitle: 'Fetch booking details from backend by id.',
    },
    profileTitle: 'Profile',
    loadingHome: 'Loading home...',
    homeLoadError: 'Unable to load home data right now.',
    allServices: {
      searchPlaceholder: 'Search for a service...',
      loadingServices: 'Loading services...',
      loadingMore: 'Loading more...',
      loadMoreCta: 'Load more',
      emptyTitle: 'No services found',
      emptySubtitle: 'Try a different keyword.',
      pullToRefreshHint: 'Pull to refresh and try again.',
    },
    bookingFlow: {
      exploreEyebrow: 'BOOK A SERVICE',
      categoryTitle: 'Choose Subcategory',
      categorySubtitle: 'Select one subcategory first, then choose services inside it.',
      serviceTitle: 'Choose Services',
      serviceSubtitle: 'Pick one or more services from this subcategory only.',
      loadingError: 'Unable to load services right now.',
      retry: 'Retry',
      categoriesLabel: 'Categories',
      subcategoryLabel: 'Subcategories',
      servicesLabel: 'Services',
      chooseSubcategoryCta: 'Choose This Subcategory',
      selectedCountSuffix: 'selected',
      noSubcategory: 'No subcategories available.',
      noService: 'No services available in this subcategory yet.',
      continueCta: 'Continue to Booking',
      detailsEyebrow: 'BOOKING DETAILS',
      detailsTitle: 'Booking Details',
      detailsSubtitle: '',
      bookingTypeLabel: 'Booking Type',
      instantBookingLabel: 'Instant Booking',
      instantBookingSubtitle: 'Fast booking using the current time window.',
      scheduledBookingLabel: 'Scheduled Booking',
      scheduledBookingSubtitle: 'Choose your preferred date and start time.',
      scheduleSectionTitle: 'Schedule',
      dateLabel: 'Date',
      datePlaceholder: 'YYYY-MM-DD',
      timeLabel: 'Time',
      timePlaceholder: 'HH:MM',
      datePickerCta: 'Choose date',
      timePickerCta: 'Choose time',
      instantBookingHint: 'Instant service will be requested right away.',
      selectedServicesTitle: 'Selected Services',
      selectedServicesCountSuffix: 'selected services',
      selectedServicesCountSingular: 'selected service',
      quantityLabel: 'Quantity',
      priceOptionsTitle: 'Price Options',
      subtotalLabel: 'Subtotal',
      lineTotalLabel: 'Total',
      includedTitle: 'What is included',
      excludedTitle: 'Not included',
      tasksNoIncluded: 'No included tasks for this service.',
      tasksNoExcluded: 'No excluded tasks for this service.',
      locationTitle: 'Location',
      locationCurrentTitle: 'Use Current Location',
      locationCurrentSubtitle: 'Auto-fill your live location and nearby address details.',
      locationManualTitle: 'Pinned Location Manually',
      locationManualSubtitle: 'Add the exact location details yourself.',
      detectedAddressLabel: 'Google Detected',
      detectedAddressSubtitle: 'Use detected address and refine details.',
      pinnedAddressLabel: 'Pinned Manually',
      pinnedAddressSubtitle: 'Manually pin coordinates and full address.',
      addressDetailsTitle: 'Pinned Location Details',
      currentLocationSummaryTitle: 'Current location summary',
      useCurrentLocationCta: 'Use current location',
      refreshingLocationLabel: 'Refreshing...',
      addressLine1Label: 'Address Line 1',
      addressLine2Label: 'Address Line 2',
      addressLine2Placeholder: 'Landmark, apartment, floor',
      areaLabel: 'Area / Locality',
      areaPlaceholder: 'Civil Lines',
      districtLabel: 'District / City',
      districtPlaceholder: 'Prayagraj',
      stateFieldLabel: 'State',
      statePlaceholder: 'Uttar Pradesh',
      pincodeLabel: 'Pincode',
      pincodePlaceholder: '211001',
      countryFieldLabel: 'Country',
      countryPlaceholder: 'India',
      latitudeLabel: 'Latitude',
      latitudePlaceholder: '25.4358',
      longitudeLabel: 'Longitude',
      longitudePlaceholder: '81.8463',
      addressPreviewTitle: 'Address Preview',
      addressPreviewPlaceholder: 'Address summary will appear here.',
      invalidCoordinatesHint: 'Add valid coordinates so workers can navigate correctly.',
      currentLocationEmptyHint: 'Current address details will appear here after location refresh.',
      missingPriceSelectionError: 'Select one price option for every chosen service before continuing.',
      invalidScheduleError: 'Enter a valid scheduled date and time.',
      slotLabel: 'Preferred Slot',
      slotMorning: 'Today Morning (9:00 AM - 12:00 PM)',
      slotAfternoon: 'Today Afternoon (12:00 PM - 4:00 PM)',
      slotEvening: 'Today Evening (4:00 PM - 8:00 PM)',
      addressLabel: 'Service Address',
      addressPlaceholder: 'House/Flat, street, landmark',
      notesLabel: 'Notes (Optional)',
      notesSimpleLabel: 'Notes',
      notesPlaceholder: 'Share entry details or specific requests',
      reviewCta: 'Review Booking',
      confirmEyebrow: 'CONFIRM BOOKING',
      confirmTitle: 'Ready to Confirm',
      summaryCategory: 'Category',
      summaryService: 'Service',
      summaryBookingType: 'Booking Type',
      summarySlot: 'Slot',
      summaryAddress: 'Address',
      summaryNotes: 'Notes',
      quantitySummaryPrefix: 'Quantity',
      statusPrefix: 'Status',
      referencePrefix: 'Ref',
      instantScheduleLabel: 'Instant booking',
      noNotes: 'No notes added',
      confirmCta: 'Confirm Booking',
      doneTitle: 'Booking Confirmed',
      doneSubtitle: 'Your request is submitted and visible in Bookings.',
      doneBookingIdPrefix: 'Booking ID',
      goBookings: 'Go to Bookings',
      backHome: 'Back to Home',
    },
  },
  profile: {
    nameFallback: 'Dellite Customer',
    phoneFallback: 'Not provided',
    roleLabel: 'Customer',
    memberSincePrefix: 'Member since',
    editProfileButton: 'Edit Profile',
    contactInfoTitle: 'Contact Info',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    notProvided: 'Not provided',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Account preferences',
    helpTitle: 'Help & Support',
    helpSubtitle: 'Get support and report issues',
    logoutTitle: 'Logout',
    logoutSubtitle: 'Sign out from this device',
    edit: {
      step: 'UPDATE PROFILE',
      titlePrefix: 'Update your',
      titleGradientWord: 'profile',
      subtitle: 'Keep your details accurate for better bookings and support.',
      emailPlaceholder: 'Enter your email address',
      saveButton: 'Save Changes',
    },
    stats: {
      bookings: 'Bookings',
      active: 'Active',
      completed: 'Completed',
    },
    referral: {
      title: 'Referral',
      menuTitle: 'Referral Program',
      menuSubtitle: 'View code and reward details',
      pageTitle: 'Refer & Earn',
      pageSubtitle: 'Invite friends and earn rewards',
      heroTitle: 'Refer & Earn',
      heroSubtitle: 'Share the love, earn rewards!',
      conversionSubtitle: 'Redeem coins for real value',
      howItWorksTitle: 'How it works',
      inviteCustomerTitle: 'Invite a Customer',
      inviteWorkerTitle: 'Invite a Worker',
      youLabelPrefix: 'YOU',
      newCustomerLabel: 'NEW CUSTOMER',
      newWorkerLabel: 'NEW WORKER',
      andLabel: 'AND',
      worthPrefix: 'Worth',
      signupLabel: 'On signup',
      triggerPillPrefix: 'On',
      shareButton: 'Share with Friends',
      codeLabel: 'Your Referral Code',
      codeFallback: 'Not available',
      copyButton: 'Copy Code',
      copySuccess: 'Referral code copied',
      infoTitle: 'How it works',
      infoText: 'Share this code with friends. Rewards are applied based on whether they join as customer or worker.',
      rewardsTitle: 'Reward Breakdown',
      rewardCustomerLabel: 'When referred user joins as CUSTOMER',
      rewardWorkerLabel: 'When referred user joins as WORKER',
      rewardUnavailable: 'Reward details will appear here soon.',
      bothRolesRuleTitle: 'Both Roles Rule',
    },
  },
  tabs: {
    homeLabel: 'Home',
    allServicesLabel: 'Services',
    bookingsLabel: 'Bookings',
    profileLabel: 'Profile',
  },
};
