function readEnvValue(...keys: string[]) {
  for (const key of keys) {
    const value = process.env[key];
    if (typeof value === 'string' && value.trim().length > 0) {
      return value.trim();
    }
  }
  return undefined;
}

export const ENV = {
  API_BASE_URL: readEnvValue('EXPO_PUBLIC_API_BASE_URL'),
  GOOGLE_MAPS_API_KEY: readEnvValue('EXPO_PUBLIC_GOOGLE_MAPS_API_KEY'),
  APP_ENV: readEnvValue('EXPO_PUBLIC_APP_ENV'),
  APP_NAME: readEnvValue('EXPO_PUBLIC_APP_NAME'),
  FIREBASE_API_KEY: readEnvValue('EXPO_PUBLIC_FIREBASE_API_KEY', 'FIREBASE_API_KEY'),
  FIREBASE_AUTH_DOMAIN: readEnvValue('EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN', 'FIREBASE_AUTH_DOMAIN'),
  FIREBASE_DATABASE_URL: readEnvValue('EXPO_PUBLIC_FIREBASE_DATABASE_URL', 'FIREBASE_DATABASE_URL'),
  FIREBASE_PROJECT_ID: readEnvValue('EXPO_PUBLIC_FIREBASE_PROJECT_ID', 'FIREBASE_PROJECT_ID'),
  FIREBASE_STORAGE_BUCKET: readEnvValue('EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET', 'FIREBASE_STORAGE_BUCKET'),
  FIREBASE_MESSAGING_SENDER_ID: readEnvValue('EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID', 'FIREBASE_MESSAGING_SENDER_ID'),
  FIREBASE_APP_ID: readEnvValue('EXPO_PUBLIC_FIREBASE_APP_ID', 'FIREBASE_APP_ID'),
  FIREBASE_MEASUREMENT_ID: readEnvValue('EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID', 'FIREBASE_MEASUREMENT_ID'),
} as const;
