export const BOOKING_STATUS = {
  SEARCHING: 'SEARCHING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export const CUSTOMER_BOOKING_TYPE = {
  INSTANT: 'INSTANT',
  SCHEDULED: 'SCHEDULED',
} as const;