export const BOOKING_STATUS = {
  CREATED: 'CREATED',
  SEARCHING: 'SEARCHING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export const BOOKING_PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
  CASH_COLLECTED: 'CASH_COLLECTED',
} as const;

export type BookingPaymentStatus = typeof BOOKING_PAYMENT_STATUS[keyof typeof BOOKING_PAYMENT_STATUS];

export const CUSTOMER_BOOKING_TYPE = {
  INSTANT: 'INSTANT',
  SCHEDULED: 'SCHEDULED',
} as const;
