export const BOOKING_STATUS = {
  SEARCHING: 'SEARCHING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export const CUSTOMER_BOOKING_TYPE = {
  INSTANT: 'INSTANT',
  SCHEDULED: 'SCHEDULED',
} as const;

export const WORKER_JOB_INVITE_STATUS = {
  VIEWED: 'VIEWED',
  NEW_JOB_REQUEST: 'NEW_JOB_REQUEST',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;